### ISSUE TITLE
Do not prefix default URL when only one locale is enabled - NOT WORKING!!!

### ISSUE THREAD

**Issue by rosolovsky** [Dynamedia/oc-posts-demo-theme#1]
Nice!!! But!
Do not prefix default URL when only one locale is enabled - NOT WORKING!!!

**Comment by robballantyne** [comment]
Hi,

This is a setting that should be defined via the RainLab.Translate config (https://github.com/rainlab/translate-plugin/blob/master/config/config.php). 

If this doesn't fix, please could you provide more detail.

Thanks

**Comment by rosolovsky** [comment]
Oh my God! Sorry!
This plugin really nice. Work great!

**Comment by robballantyne** [comment]
No problem, happy to help!
